In [ ]:
import numpy as np
import statistics
from scipy import linalg
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
list1=[5,4,3,2,1]

In [ ]:
print(list1)

[5, 4, 3, 2, 1]


In [ ]:
import math

In [ ]:
print(math.floor(1.9))

1


In [ ]:
print(math.ceil(1.9))

2


In [ ]:
print(math.sqrt(13))

3.605551275463989


In [ ]:
print(math.isqrt(13))

3


In [ ]:
print(math.gcd(6,12))

6


In [ ]:
print(math.trunc(4.5))
print(math.factorial(3))
print(math.log(100))
print(math.pow(2,3))

4
6
4.605170185988092
8.0


In [ ]:
print(math.pow(2,3))

8.0


Array attributes

In [ ]:
arr=np.array([4,6,8,2,1])
print("Size:",arr.size)
print("Shape:",arr.shape)
print("dimension:",arr.ndim)
print("datatype:",arr.dtype)
print("transpose:",arr.T)
print("ItemSize:",arr.itemsize)

Size: 5
Shape: (5,)
dimension: 1
datatype: int64
transpose: [4 6 8 2 1]
ItemSize: 8


numpy Methods


In [ ]:
print("Sort:",np.sort(arr))
print("SUM:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Maximum",np.max(arr))
print("Minimum:",np.min(arr))
print("Standard Deviation:",np.std(arr))
deg=np.array([0,30,45,60,90])
rad=np.radians(deg)
print("sin:",np.sin(rad))
print("cos:",np.cos(rad))
print("tan:",np.tan(rad))

Sort: [1 2 4 6 8]
SUM: 21
Mean: 4.2
Maximum 8
Minimum: 1
Standard Deviation: 2.5612496949731396
sin: [0.         0.5        0.70710678 0.8660254  1.        ]
cos: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tan: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [ ]:
val=np.array([-1,0,0.5,1])
print("arcsin:",np.arcsin(val))
print("arccos:",np.arccos(val))
print("arctan:",np.arctan(val))

arcsin: [-1.57079633  0.          0.52359878  1.57079633]
arccos: [3.14159265 1.57079633 1.04719755 0.        ]
arctan: [-0.78539816  0.          0.46364761  0.78539816]


In [ ]:
print(np.random.rand(2,3))
print(np.ones([2,3]))
print(np.zeros([2,3]))
print("Identity Matrix:")
print(np.eye(3,3))
print("shape:",np.shape(arr))
print("Reshaped:",np.reshape(arr,(5,1)))
print("product:",np.dot(arr,arr))

[[0.23769619 0.13971567 0.92913848]
 [0.57521481 0.21388804 0.05966749]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
shape: (5,)
Reshaped: [[4]
 [6]
 [8]
 [2]
 [1]]
product: 121


In [ ]:
mat=np.array([[1,1,3],[0,1,1],[0,0,1]])
print("determinant:",linalg.det(mat))
eig_v,eig_vec=linalg.eig(mat)
print("eigen values:",eig_v)
print("eigen vectors:",eig_vec)
print("Inverse:",linalg.inv(mat))

determinant: 0.9999999999999999
eigen values: [1.+0.j 1.+0.j 1.+0.j]
eigen vectors: [[ 1.00000000e+00 -1.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  4.93038066e-32]]
Inverse: [[ 1. -1. -2.]
 [ 0.  1. -1.]
 [ 0.  0.  1.]]


In [ ]:
data=np.array([1,2,3,4,5,6,7,8])
print("2D:")
print(np.reshape(data,(2,4)))
print("3D:")
print(np.reshape(data,(2,2,2)))

2D:
[[1 2 3 4]
 [5 6 7 8]]
3D:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:

list2=[1,3,5,7,8]
series=pd.Series(list2)
print(series)

print("Index:",series.index)
print("Values:",series.values)

np_array=np.array([1,3,5,7,8])
series2=pd.Series(np_array)
print("Array:",np_array)
print("Series:",series2)

0    1
1    3
2    5
3    7
4    8
dtype: int64
Index: RangeIndex(start=0, stop=5, step=1)
Values: [1 3 5 7 8]
Array: [1 3 5 7 8]
Series: 0    1
1    3
2    5
3    7
4    8
dtype: int64


In [ ]:
ser=pd.Series(list2,index=['a','b','c','d','e'])
print(ser)
print("position 2:",ser.iloc[2])
print("value at index 'a':",ser['a'])

a    1
b    3
c    5
d    7
e    8
dtype: int64
position 2: 5
value at index 'a': 1


In [ ]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
data=pd.read_csv(url)
print("First 5:",data.head())
print("last 5:",data.tail())

First 5:    sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
last 5:      sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica


In [ ]:
print("shape:",data.shape)
print("column:",data.columns)

shape: (150, 5)
column: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')
